---

pipeline:
  deploy:
    image: appleboy/drone-scp
    settings:
      strip_components: 1
      host:
        - timetime.hyteck.de
      username: time
      target: /var/www/time/
      source: ./
      key:
        from_secret: ssh_key
